theme: jekyll-theme-minimal
title: KETCube EDU - Edukační balíček pro Arduino
description: Edukační balíček pro Arduino na platformě KETCube
logo: logo.png
logo_oshw: oshw-logo.png
url_oshw: https://www.oshwa.org/
show_downloads: true
github:
  maintainer: SmartCampus ZČU Team
  sponsor: City of Pilsen
  maintainer_url: https://github.com/SmartCAMPUSZCU
  logo_mt: sc-logo.png
  url_mt: https://www.smartcampus.cz/
  logo_sponsor: plzen-logo.png
  url_sponsor: https://www.plzen.eu/
  is_project_page: false
  arduino_name: Balíček pro Arduino IDE
  arduino_json_url: https://edu.ketcube.cz/files/package_ketcube_index.json
#  arduino_ar_url: https://github.com/SmartCAMPUSZCU/KETCube-arduino/releases/latest/download/KETCube-Arduino-board.tar.gz
#  arduino_lib_url: https://github.com/SmartCAMPUSZCU/KETCube-arduino/releases/latest/download/KETCube-Arduino-lib.zip
  arduino_ar_url: https://edu.ketcube.cz/files/releases/v0.2.5/KETCube-Arduino-board.tar.gz
  arduino_lib_url: https://edu.ketcube.cz/files/releases/v0.2.5/KETCube-Arduino-lib.zip
  arduino_apidoc_url: https://edu.ketcube.cz/files/apidoc/
  arduino_repository_url: https://github.com/SmartCAMPUSZCU/KETCube-arduino
  docs_name: Dokumentace
  docs_datasheet: https://github.com/SmartCAMPUSZCU/KETCube-docs/blob/master/KETCubeDatasheet.pdf
  docs_appnotes: https://github.com/SmartCAMPUSZCU/KETCube-docs/tree/master/appNotes
  docs_repository_url: https://github.com/SmartCAMPUSZCU/KETCube-docs/tree/master
  
  
