theme: jekyll-theme-minimal
title: KETCube EDU - Edukační balíček pro Arduino
description: Edukační balíček pro Arduino na platformě KETCube
logo: logo.png
logo_oshw: oshw-logo.png
show_downloads: true
github:
  maintainer: SmartCampus ZČU Team
  sponsor: City of Pilsen
  maintainer_url: https://github.com/SmartCAMPUSZCU
  logo_mt: sc-logo.png
  logo_sponsor: plzen-logo.png
  is_project_page: false
  arduino_name: Balíček pro Arduino IDE
  arduino_json_url: https://edu.ketcube.cz/files/package_ketcube_index.json
  arduino_ar_url: https://edu.ketcube.cz/files/ketcube-arduino-0.2.0.tar.gz
  arduino_lib_url: https://edu.ketcube.cz/files/KETCube_Arduino-lib-0.2.0.zip
  arduino_apidoc_url: https://edu.ketcube.cz/files/apidoc/
  arduino_repository_url: https://github.com/SmartCAMPUSZCU/KETCube-arduino
  docs_name: Dokumentace
  docs_datasheet: https://github.com/SmartCAMPUSZCU/KETCube-docs/blob/refactoring_0.2/KETCubeDatasheet.pdf
  docs_appnotes: https://github.com/SmartCAMPUSZCU/KETCube-docs/tree/refactoring_0.2/appNotes
  docs_repository_url: https://github.com/SmartCAMPUSZCU/KETCube-docs/tree/refactoring_0.2
  
  
